"""empty message

Revision ID: 06c4be32ce97
Revises: e50f47b49782
Create Date: 2020-09-17 08:41:28.003571

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '06c4be32ce97'
down_revision = 'e50f47b49782'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('called', sa.Column('sala', sa.String(length=20), nullable=False))
    op.drop_column('called', 'room')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('called', sa.Column('room', mysql.VARCHAR(length=15), nullable=False))
    op.drop_column('called', 'sala')
    # ### end Alembic commands ###
