"""empty message

Revision ID: 16d4511b1ff9
Revises: dfedd18fcadd
Create Date: 2020-09-07 12:05:40.320703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16d4511b1ff9'
down_revision = 'dfedd18fcadd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('status', table_name='called')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('status', 'called', ['status'], unique=True)
    # ### end Alembic commands ###
