"""empty message

Revision ID: 18d0450f8ebf
Revises: 87ea86b776b7
Create Date: 2020-09-14 13:40:15.774173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18d0450f8ebf'
down_revision = '87ea86b776b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enterprise', sa.Column('email', sa.String(length=120), nullable=False))
    op.add_column('enterprise', sa.Column('nickname', sa.String(length=80), nullable=False))
    op.create_unique_constraint(None, 'enterprise', ['nickname'])
    op.create_unique_constraint(None, 'enterprise', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'enterprise', type_='unique')
    op.drop_constraint(None, 'enterprise', type_='unique')
    op.drop_column('enterprise', 'nickname')
    op.drop_column('enterprise', 'email')
    # ### end Alembic commands ###
