"""empty message

Revision ID: 1c669d73b297
Revises: 06c4be32ce97
Create Date: 2020-09-17 08:46:58.187684

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1c669d73b297'
down_revision = '06c4be32ce97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('called', 'sala')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('called', sa.Column('sala', mysql.VARCHAR(length=20), nullable=False))
    # ### end Alembic commands ###
