"""empty message

Revision ID: 7287f7b21090
Revises: 8041cb310999
Create Date: 2020-09-17 07:45:17.152385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7287f7b21090'
down_revision = '8041cb310999'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('called', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'called', 'enterprise', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'called', type_='foreignkey')
    op.drop_column('called', 'parent_id')
    # ### end Alembic commands ###
