"""empty message

Revision ID: 8041cb310999
Revises: 18d0450f8ebf
Create Date: 2020-09-16 14:41:52.923863

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8041cb310999'
down_revision = '18d0450f8ebf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('called_ibfk_1', 'called', type_='foreignkey')
    op.drop_column('called', 'parent_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('called', sa.Column('parent_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('called_ibfk_1', 'called', 'enterprise', ['parent_id'], ['id'])
    # ### end Alembic commands ###
