"""empty message

Revision ID: 87ea86b776b7
Revises: ccbeab18d978
Create Date: 2020-09-14 13:11:47.354062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87ea86b776b7'
down_revision = 'ccbeab18d978'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enterprise', sa.Column('password', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enterprise', 'password')
    # ### end Alembic commands ###
