"""empty message

Revision ID: aeeb1a084c3a
Revises: 1c669d73b297
Create Date: 2020-09-17 08:58:23.480755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeeb1a084c3a'
down_revision = '1c669d73b297'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('called', sa.Column('room', sa.String(length=280), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('called', 'room')
    # ### end Alembic commands ###
