"""empty message

Revision ID: ba81ba533d47
Revises: 5b871926e80b
Create Date: 2020-09-01 10:23:42.104186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba81ba533d47'
down_revision = '5b871926e80b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'cooker', ['nickname'])
    op.drop_index('brand', table_name='order')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('brand', 'order', ['brand'], unique=True)
    op.drop_constraint(None, 'cooker', type_='unique')
    # ### end Alembic commands ###
