"""empty message

Revision ID: dfedd18fcadd
Revises: 
Create Date: 2020-09-04 15:18:41.924805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfedd18fcadd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cooker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('enterprise', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nickname')
    )
    op.create_table('called',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('called_code', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('espera', 'listo', 'entregado', 'cancelado', 'proceso'), nullable=False),
    sa.Column('time', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=170), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['cooker.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('called_code'),
    sa.UniqueConstraint('status')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('called')
    op.drop_table('cooker')
    # ### end Alembic commands ###
