"""empty message

Revision ID: e50f47b49782
Revises: 7287f7b21090
Create Date: 2020-09-17 08:00:45.333063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e50f47b49782'
down_revision = '7287f7b21090'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('called', sa.Column('room', sa.String(length=15), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('called', 'room')
    # ### end Alembic commands ###
